<?php
/** Landing page principal. @package WazzaAPI */
get_header();
$features = array('Inbox Omnichannel','IA Generativa','Flow Builder','CRM','Campanhas','RAG','Base de Conhecimento','MCP','Memórias','API Oficial WhatsApp','Analytics','Relatórios','Agendamentos','Webhooks','Integrações','Etiquetas','Funis','Pipeline','Tarefas','Usuários','Permissões','LGPD','Segurança');
?>
<section class="hero" aria-labelledby="hero-title">
    <div class="orb orb-a" aria-hidden="true"></div><div class="orb orb-b" aria-hidden="true"></div>
    <div class="container hero-grid">
        <div data-animate="up">
            <span class="eyebrow">✦ <?php esc_html_e('WhatsApp Business com IA, RAG e automações', 'wazzaapi'); ?></span>
            <h1 id="hero-title"><?php esc_html_e('Transforme seu WhatsApp em uma máquina inteligente de atendimento e vendas.', 'wazzaapi'); ?></h1>
            <p class="lead"><?php esc_html_e('Centralize conversas, automatize processos e aumente resultados com Inteligência Artificial.', 'wazzaapi'); ?></p>
            <div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/contato/')); ?>"><?php esc_html_e('Testar Gratuitamente', 'wazzaapi'); ?></a><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/contato/')); ?>"><?php esc_html_e('Agendar Demonstração', 'wazzaapi'); ?></a></div>
            <div class="hero-stats"><div class="stat"><strong data-count="117">0</strong><span>% taxa de resposta</span></div><div class="stat"><strong data-count="243">0</strong><span>mensagens hoje</span></div><div class="stat"><strong data-count="99">0</strong><span>% disponibilidade</span></div></div>
        </div>
        <div class="platform-mockup parallax" aria-label="Mockup moderno da plataforma" data-animate="left">
            <div class="mockup-top" aria-hidden="true"><span></span><span></span><span></span></div>
            <div class="dashboard-ui">
                <aside><div class="mini-logo">W</div><span></span><span></span><span></span><span></span><span></span></aside>
                <section><div class="dash-head"><b>Boa noite, Gabriel 👋</b><button>+ Novo fluxo</button></div><div class="kpi-row"><div>Conversas<br><b>1</b></div><div>Mensagens<br><b>243</b></div><div>Resposta<br><b>117%</b></div></div><svg class="chart" viewBox="0 0 520 190" role="img" aria-label="Gráfico de mensagens"><path d="M0 170 C60 40 110 50 170 82 S270 190 340 70 455 30 520 150"/><path class="blue" d="M0 170 C70 85 120 90 190 105 S275 185 350 90 455 28 520 150"/></svg></section>
                <div class="phone"><b>IA Wazza</b><p>Olá! Consultei sua base RAG e já encontrei o melhor plano.</p><em>Transferir para humano</em></div>
            </div>
        </div>
    </div>
</section>
<section class="section logos" aria-labelledby="clientes-title"><div class="container"><div class="section-header"><span class="eyebrow">Confiança</span><h2 id="clientes-title">Empresas que confiam na WazzaAPI.</h2></div><div class="logo-cloud" data-animate="up"><div>ATLAS</div><div>NOVA</div><div>PULSE</div><div>ORBIT</div><div>VERTEX</div></div></div></section>
<section class="section section-muted" id="solucoes" aria-labelledby="func-title"><div class="container"><div class="section-header"><span class="eyebrow">Funcionalidades</span><h2 id="func-title">Tudo para escalar relacionamento, vendas e suporte.</h2><p>Um ecossistema SaaS completo, visualmente simples e tecnicamente poderoso.</p></div><div class="feature-grid"><?php foreach ($features as $i=>$feature) : ?><article class="feature-card hover-lift" data-animate="up"><span class="icon-spark"><?php echo esc_html(array('💬','✨','⚙️','📈','📣','🧠','📚','🔌','🧩','✅','📊','📑','🗓️','🔁','🔗','🏷️','🧭','🚀','✓','👥','🔐','⚖️','🛡️')[$i]); ?></span><h3><?php echo esc_html($feature); ?></h3><p><?php esc_html_e('Operação conectada com automações, dados e experiência premium para o cliente final.', 'wazzaapi'); ?></p></article><?php endforeach; ?></div></div></section>
<section class="section" id="recursos" aria-labelledby="timeline-title"><div class="container"><div class="section-header"><span class="eyebrow">Como funciona</span><h2 id="timeline-title">Da primeira mensagem à venda concluída.</h2></div><ol class="timeline" data-animate="up"><li>Cliente envia mensagem</li><li>IA interpreta intenção</li><li>Fluxo automatizado</li><li>Consulta Base RAG</li><li>Executa ações</li><li>Transfere para humano quando necessário</li><li>Venda ou atendimento concluído</li></ol></div></section>
<section class="section section-dark" aria-labelledby="ai-title"><div class="container split"><div data-animate="up"><span class="eyebrow">Inteligência Artificial</span><h2 id="ai-title">IA generativa com contexto, memória e provedores flexíveis.</h2><p>Use NLP, embeddings, base vetorizada, RAG, memórias persistentes e modelos configuráveis com Gemini, OpenAI, Claude ou provedores customizados.</p><div class="chips"><span>Gemini</span><span>OpenAI</span><span>Claude</span><span>Custom</span></div></div><div class="ai-panel glow" data-animate="left"><code>intent.detect()</code><code>rag.search("política comercial")</code><code>crm.updateLead()</code><code>human.handoff(if needed)</code></div></div></section>
<section class="section" aria-labelledby="flow-title"><div class="container split"><div class="flow-canvas" data-animate="up"><div>Mensagem recebida</div><div>Condição</div><div>Delay</div><div>IA</div><div>Ação externa</div></div><div data-animate="left"><span class="eyebrow">Flow Builder</span><h2 id="flow-title">Editor visual para desenhar jornadas sem fricção.</h2><p>Drag and drop, condições, escolhas, delays, integrações, IA e ações em uma experiência clara para times de operação.</p></div></div></section>
<section class="section section-muted" aria-labelledby="inbox-title"><div class="container split"><div><span class="eyebrow">Inbox</span><h2 id="inbox-title">Atendimento multiusuário no mesmo número.</h2><p>Assuma conversas no desktop ou mobile, acompanhe histórico, etiquetas e transferências entre equipes com governança.</p></div><div class="device-stack" data-animate="left"><div class="laptop"><b>Inbox Omnichannel</b><p>Suporte - Gabriel · Aguardando</p><p>Documento enviado</p></div><div class="mobile"><b>Wazza</b><p>Cliente qualificado pela IA.</p></div></div></div></section>
<section class="section" id="integracoes" aria-labelledby="mcp-title"><div class="container cards-3"><article class="card hover-lift"><h2 id="mcp-title">MCP</h2><p>Conecte servidores MCP, integre sistemas e permita que a IA execute ferramentas externas com segurança.</p></article><article class="card hover-lift"><h2>Base de Conhecimento</h2><p>Upload PDF/TXT, vetorização, consulta contextual e respostas com RAG para manter o atendimento preciso.</p></article><article class="card hover-lift"><h2>Relatórios</h2><p>Dashboards modernos, KPIs e gráficos SVG para acompanhar conversas, conversões, campanhas e SLA.</p></article></div></section>
<section class="section section-muted" id="precos" aria-labelledby="price-title"><div class="container"><div class="section-header"><span class="eyebrow">Preços</span><h2 id="price-title">Planos elegantes para cada estágio da operação.</h2></div><div class="pricing"><article class="price-card"><h3>Starter</h3><strong>R$ 197</strong><p>/mês</p><ul><li>Inbox e CRM</li><li>Fluxos essenciais</li><li>1 número WhatsApp</li></ul><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/contato/')); ?>">Contratar</a></article><article class="price-card featured"><h3>Scale</h3><strong>R$ 497</strong><p>/mês</p><ul><li>IA generativa + RAG</li><li>Campanhas e webhooks</li><li>Relatórios avançados</li></ul><a class="btn btn-primary" href="<?php echo esc_url(home_url('/contato/')); ?>">Contratar</a></article><article class="price-card"><h3>Enterprise</h3><strong>Custom</strong><p>sob consulta</p><ul><li>MCP e integrações</li><li>Permissões e LGPD</li><li>Suporte prioritário</li></ul><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/contato/')); ?>">Contratar</a></article></div></div></section>
<section class="section"><div class="container"><div class="cta" data-animate="up"><div><span class="eyebrow">Comece agora</span><h2>Pronto para transformar seu WhatsApp em um motor de vendas?</h2><p>Teste gratuitamente uma operação mais inteligente, escalável e confiável.</p></div><a class="btn btn-primary" href="<?php echo esc_url(home_url('/contato/')); ?>">Testar Gratuitamente</a></div></div></section>
<?php get_footer(); ?>
